version: '3.8'

services:
  app:
    image: groceryapi:latest
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/grocery_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db # Ensures the database starts before the app

  db:
    image: mysql:8.0.27
    environment:
      DATABASE-HOST: docker-mysql
      DATABASE-PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grocery_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
